required:
    host_name:   'http://health-equity.lib.umd.edu'
    query_path:  'cgi/export/{0}/DC/minorityhealth-archive-{0}.txt'
    id_range:    '1-4300'
    id_file:     'data/ids.txt'
    local_cache: 'data/eprints'
    saf_dir:     'data/saf'
    log_dir:     'logs'

extra:
    move_aside:   {module: .add_keywords, parameters: [add_keywords.csv]}
    add_keywords: {module: .move_aside,   parameters: [move_aside.txt]}
    update_links: {module: .update_links, parameters: None}
