host_name:   'http://health-equity.lib.umd.edu'
query_path:  'cgi/export/{0}/DC/minorityhealth-archive-{0}.txt'
id_range:    '1-4300'
local_cache: 'data/eprints'
saf_dir:     'data/saf'
log_dir:     'logs'

