# Eprints server configuration
EPRINTS_HOST:    "http://health-equity.lib.umd.edu"
EPRINTS_QUERY:   "cgi/export/{0}/DC/{1}-{0}.txt"
EPRINTS_ARCHIVE: "minorityhealth-archive"
EPRINTS_RANGE:   "1-5000"
EPRINTS_LOCAL:   "data/export"

# Dspace server configuration
DSPACE_HOST:     "http://drum.lib.umd.edu"
DSPACE_SAF_ROOT: "data/saf"
DSPACE_HANDLE:   ""

# Local storage configuration
LOG_DIR:          "logs"
MAPFILE:          "mapfile.csv"
ERRFILE:          "errors.csv"
