# Eprints server configuration
HOST:           "http://health-equity.lib.umd.edu"
QUERY_TEMPLATE: "http://health-equity.lib.umd.edu/cgi/export/{0}/DC/{1}-{0}.txt"
ARCHIVE_NAME:   "minorityhealth-archive"
EXPORT_RANGE:   "1-5000"

# Dspace server configuration
DESTINATION:    "http://drum.lib.umd.edu"
SAF_PACKAGE:    "data/saf"

# Local storage configuration
MAPFILE:        "mapfile.csv"
LOG_DIR:        "logs"
EPRINT_ERRORS:  "eprint_errors.csv"
EPRINT_EXPORT:  "data/export/"
